### ISSUE TITLE
Proper cleanup

### ISSUE THREAD

**Issue by claustres** [kalisio/kApp#15]
For now some things are not correctly cleaned:
* [x] on user removal from an org
  * [x] should remove all group authorisations (thus unsubscribe associated topics)
  * [x] should unsubscribe org topic
  * [x] should remove org tags (and thus unsubscribe tag topics on all members)
  * ~~should remove it from any event it is registered as a single user~~
* [x] on user removal from the system
  * [x] should remove all org authorisations (thus unsubscribe associated topics)
  * [x] should remove all tags (thus associated topics)
  * [x] should remove avatar
* [x] when a new device is registered
  * [x] should remove old one if any
  * [x] should also unsubscribe all topics on old device (according to SNS docs https://docs.aws.amazon.com/sns/latest/api/API_DeleteEndpoint.html)
* [x] when an org is removed
  * [x] should remove all groups (thus destroy/unsubscribe associated topics)
  * [x] should remove all tag topics by removing tags
  * ~~should remove all events~~
  * ~~should remove all storage objects (for now removing events should be sufficient)~~

**Comment by claustres** [comment]
This will require the reordering of some hooks, eg:
* we remove the private org after the user removal but then the authorisations cannot be unset on the user because it does not exist anymore in the DB

This might be a little tricky because in after hooks we have the object in the result while in before hooks we might only have the ID. We might also have a symmetry: what is done on creation in an after hook should be done on removal in a before hook.

**Comment by claustres** [comment]
In order to simplify a little bit we should not allow org removal until it is at least partly empty (eg events, groups).

**Comment by cnouguier** [comment]
Why not. It implies that we provide some functionnalities to easily clean the organisation such as deleting multiple elements

**Comment by claustres** [comment]
When deleting a user we should remove it from all orgs unless he is the only owner and in this case we delete the org.

**Comment by cnouguier** [comment]
To simplify the hook chain, we need to:
* [ ] prevent the user deletion if the user owns at least one organisation
* [ ] prevent the organisation deletion if it contains a group
