### ISSUE TITLE
Abilities not correctly updated when changing tags on a member

### ISSUE THREAD

**Issue by claustres** [kalisio/kApp#22]
Linked to the fact that only authorisations change abilities for now but updating tag should as well.

**Comment by claustres** [comment]
Seems to be related to the fact we use the members service in this case and not the user service, so that the authorisation mixin dose not work as expected.

**Comment by claustres** [comment]
We should implement something similar to what is done here https://github.com/kalisio/kCore/blob/master/src/client/index.js#L42.

**Comment by claustres** [comment]
The problem is not on the client side, events are correctly received on the users service, but on the server side abilities are not updated on user patch only on authorisation changes. So if you create an event targetting a tag after removing it from the user the find request still show the event while the client side abilities are correct (no more actions, etc.).

**Comment by cnouguier** [comment]
Edit a member and assign him two tags => ok
Redit the same member and remove one tag => all the tags have disappeared

**Comment by cnouguier** [comment]
Seems to be different and creating new issue: https://github.com/kalisio/kCore/issues/58
